Repository traefik/faency, pull requests merged in 2019-12, with the labels that each got.

#8 Add <Input> Component
  src/components/Input.story.tsx
  src/components/Input.tsx
  src/index.ts
  src/theme.ts
Labels: status/3-needs-merge

#4 Add <Nav> , <NavItem> and <NavGroup> components
  src/components/Nav.story.tsx
  src/components/Nav.tsx
  src/components/Text.tsx
  src/fonts/Nunito-SemiBold.woff
  src/fonts/Nunito-SemiBold.woff2
  src/fonts/index.ts
  src/index.ts
  src/theme.ts
Labels: bot/need-human-merge, status/3-needs-merge

#9 Add <Chip> component
  src/components/Chip.story.tsx
  src/components/Chip.tsx
  src/index.ts
  src/theme.ts
Labels: status/3-needs-merge

#10 Add styling when a Tr is hovered + some minor style fixes
  src/components/Table.tsx
  src/theme.ts
Labels: status/3-needs-merge

#16 fix: Chip should be a directive from an inline element
  src/components/Chip.story.tsx
  src/components/Chip.tsx
Labels: status/3-needs-merge

#15 fix: Chip background colors
  src/components/Chip.story.tsx
  src/components/Chip.tsx
  src/theme.ts
Labels: status/3-needs-merge

#17 fix: grey background color for default buttons on windows
  .gitignore
  src/components/Button.tsx
Labels: status/3-needs-merge

#5 Add <SubNav> and <SubNavItem> components
  src/components/SubNav.story.tsx
  src/components/SubNav.tsx
  src/index.ts
Labels: status/3-needs-merge

#11 Add <Loading> component
  src/components/Loading.story.tsx
  src/components/Loading.tsx
Labels: status/3-needs-merge

#18 Bump to v0.1.0
  package.json
Labels: status/3-needs-merge

#20 fix: chip are now using nowrap
  src/components/Chip.tsx
Labels: enhancement, status/3-needs-merge

#27 refactor: remove radix-system dependency
  .storybook/config.js
  package-lock.json
  package.json
  src/components/Box.story.tsx
  src/components/Button.story.tsx
  src/components/Button.tsx
  src/components/Card.tsx
  src/components/Chip.story.tsx
  src/components/Chip.tsx
  src/components/Heading.story.tsx
  src/components/Heading.tsx
  src/components/Input.story.tsx
  src/components/Input.tsx
  src/components/Loading.tsx
  src/components/Nav.story.tsx
  src/components/Nav.tsx
  src/components/SubNav.story.tsx
  src/components/SubNav.tsx
  src/components/Text.tsx
  src/theme.ts
Labels: status/3-needs-merge

#28 Add ToggleButtonGroup component
  src/components/ToggleButton.story.tsx
  src/components/ToggleButton.tsx
Labels: status/3-needs-merge

#32 fix: correct NavItem type issue + import of styled-system
  package-lock.json
  package.json
  src/components/Nav.story.tsx
  src/components/Nav.tsx
  src/components/SubNav.tsx
  src/types/index.d.ts
Labels: status/3-needs-merge

#33 chore: bump to v0.2.1
  package-lock.json
  package.json
Labels: status/3-needs-merge
