Repository traefik/faency, pull requests merged in 2020-03, with the labels that each got.

#70 feat: add dark mode
  README.md
  packages/faency/.storybook/config.js
  packages/faency/package.json
  packages/faency/src/Provider.tsx
  packages/faency/src/components/Button.tsx
  packages/faency/src/components/Card.tsx
  packages/faency/src/components/CardLink.tsx
  packages/faency/src/components/Chip.tsx
  packages/faency/src/components/Heading.tsx
  packages/faency/src/components/Input.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/components/Nav/Nav.tsx
  packages/faency/src/components/Select.tsx
  packages/faency/src/components/SubNav.tsx
  packages/faency/src/components/Table.tsx
  packages/faency/src/components/Text.tsx
  packages/faency/src/components/ToggleButton.tsx
  packages/faency/src/components/Tooltip/components/TooltipOverlay.tsx
  packages/faency/src/dark-theme.ts
  packages/faency/src/hooks/use-theme.ts
  packages/faency/src/index.ts
  packages/faency/src/theme.ts
  packages/website/package.json
  packages/website/src/App.js
  packages/website/src/components/CodeBlock.js
  packages/website/src/components/Divider.js
  packages/website/src/components/Layout.js
  packages/website/src/components/Link.js
  packages/website/src/components/NavItem.js
  packages/website/src/components/SystemPropsTable.js
  packages/website/src/components/ThemeSection.js
  packages/website/src/docs/checkbox.mdx
  packages/website/src/docs/getting-started.mdx
  packages/website/src/docs/nav.mdx
  packages/website/src/docs/radio.mdx
  packages/website/src/docs/select.mdx
  packages/website/src/templates/doc-page.js
  packages/website/src/wrapPageElement.js
  packages/website/static/logo-white.png
  yarn.lock
Labels: status/3-needs-merge

#76 chore: update way of deploying using new project monorepo architecture
  .travis.yml
Labels: status/3-needs-merge

#77 fix: enable builds on *@*.*.* tags instead of v*.*.*
  lerna.json
Labels: status/3-needs-merge

#79 fix: add MenuToggle component to toggle mobile doc menu
  packages/website/src/App.js
  packages/website/src/components/Divider.js
  packages/website/src/components/MenuToggle.js
  packages/website/src/wrapPageElement.js
Labels: status/3-needs-merge

#81 chore:bump to v0.4.0
  packages/faency/package.json
  packages/website/package.json
Labels: status/3-needs-merge

#82 chore: add lerna-debug to gitgnore
  .gitignore
Labels: status/3-needs-merge

#83 Fix default dark mode value
  packages/website/src/App.js
Labels: status/3-needs-merge

#85 fix: set default dark mode value to false
  packages/website/src/App.js
Labels: status/3-needs-merge

#80 Add Dropdown and Menu components
  packages/faency/src/components/DropdownMenu.story.tsx
  packages/faency/src/components/DropdownMenu.test.tsx
  packages/faency/src/components/DropdownMenu.tsx
  packages/faency/src/components/Menu.story.tsx
  packages/faency/src/components/Menu.tsx
  packages/faency/src/components/ToggleButton.test.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/dropdown.mdx
  packages/website/src/docs/menu.mdx
Labels: status/3-needs-merge

#87 fix: set useDarkMode default value everywhere
  packages/website/src/components/CodeBlock.js
  packages/website/src/components/NavItem.js
  packages/website/src/wrapPageElement.js
Labels: status/3-needs-merge

#88 feat: add switch component
  package.json
  packages/faency/package.json
  packages/faency/src/components/Box.tsx
  packages/faency/src/components/Button.tsx
  packages/faency/src/components/Card.tsx
  packages/faency/src/components/CardLink.tsx
  packages/faency/src/components/Checkbox.tsx
  packages/faency/src/components/Chip.tsx
  packages/faency/src/components/DropdownMenu.tsx
  packages/faency/src/components/Flex.tsx
  packages/faency/src/components/Heading.tsx
  packages/faency/src/components/Input.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/components/Loading.tsx
  packages/faency/src/components/Menu.tsx
  packages/faency/src/components/Nav/Nav.tsx
  packages/faency/src/components/Radio.tsx
  packages/faency/src/components/Select.tsx
  packages/faency/src/components/Switch.story.tsx
  packages/faency/src/components/Switch.test.tsx
  packages/faency/src/components/Switch.tsx
  packages/faency/src/components/Text.tsx
  packages/faency/src/components/ToggleButton.tsx
  packages/faency/src/components/Tooltip/Tooltip.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/switch.mdx
  yarn.lock
Labels: status/3-needs-merge

#92 fix: make active state works in prod
  packages/website/src/App.js
Labels: status/3-needs-merge

#91 Proposal: Add default value to Description column in Docs
  packages/website/src/components/PropsTable.js
Labels: kind/proposal, status/3-needs-merge

#90 Fix tests and warnings on Docs website
  .travis.yml
  package.json
  packages/faency/package.json
  packages/faency/src/components/Button.test.tsx
  packages/faency/src/components/Card.test.tsx
  packages/faency/src/components/CardLink.test.tsx
  packages/faency/src/components/Chip.test.tsx
  packages/faency/src/components/DropdownMenu.test.tsx
  packages/faency/src/components/FormMessage.test.tsx
  packages/faency/src/components/Heading.test.tsx
  packages/faency/src/components/Input.test.tsx
  packages/faency/src/components/InputTags.story.tsx
  packages/faency/src/components/InputTags.test.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/components/Select.test.tsx
  packages/faency/src/components/Text.test.tsx
  packages/faency/src/hooks/use-click-outside.tsx
  packages/faency/src/hooks/use-key-listener.tsx
  packages/website/src/App.js
  packages/website/src/components/CodeBlock.js
  packages/website/src/components/Container.js
  packages/website/src/components/Layout.js
  packages/website/src/components/List.js
  packages/website/src/components/MenuToggle.js
  yarn.lock
Labels: status/3-needs-merge

#96 feat: add skeleton loading components
  packages/faency/src/components/Skeleton.story.tsx
  packages/faency/src/components/Skeleton.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/skeleton.mdx
Labels: status/3-needs-merge

#98 Add Theme Switcher to Docs Website
  packages/website/src/wrapPageElement.js
Labels: status/3-needs-merge

#89 Add Avatar component
  packages/faency/src/components/Avatar.story.tsx
  packages/faency/src/components/Avatar.test.tsx
  packages/faency/src/components/Avatar.tsx
  packages/faency/src/dark-theme.ts
  packages/faency/src/index.ts
  packages/faency/src/theme.ts
  packages/website/src/docs/avatar.mdx
  packages/website/src/templates/doc-page.js
Labels: status/3-needs-merge

#95 Add a PropRender component and update Docs to use it
  packages/faency/package.json
  packages/website/package.json
  packages/website/src/components/PropRender.js
  packages/website/src/components/PropsTable.js
  yarn.lock
Labels: status/3-needs-merge

#99 feat: add grid component
  packages/faency/src/components/Grid.story.tsx
  packages/faency/src/components/Grid.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/grid.mdx
Labels: status/3-needs-merge

#101 fix: doc website issues on gh-pages
  packages/website/gatsby-config.js
  packages/website/package.json
  packages/website/src/App.js
  packages/website/src/components/CodeBlock.js
  packages/website/src/components/NavItem.js
  packages/website/src/wrapPageElement.js
  yarn.lock
Labels: status/3-needs-merge

#102 chore: bump to v0.5.0
  packages/faency/package.json
  packages/website/package.json
Labels: status/3-needs-merge

#100 Fix incompatibility problem between arrow navigation dependency and Jest
  packages/faency/package.json
  packages/faency/src/components/ArrowNav.tsx
  packages/faency/src/components/InputTags.test.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/hooks/use-key-listener.tsx
  packages/faency/src/types/index.d.ts
  yarn.lock
Labels: status/3-needs-merge

#103 Export all types from Components and from Faency index
  packages/faency/src/components/Avatar.tsx
  packages/faency/src/components/Box.tsx
  packages/faency/src/components/Button.tsx
  packages/faency/src/components/Card.tsx
  packages/faency/src/components/Checkbox.tsx
  packages/faency/src/components/Flex.tsx
  packages/faency/src/components/FormMessage.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/components/Loading.tsx
  packages/faency/src/components/Nav/Nav.tsx
  packages/faency/src/components/Nav/index.ts
  packages/faency/src/components/Radio.tsx
  packages/faency/src/components/Skeleton.tsx
  packages/faency/src/components/SubNav.tsx
  packages/faency/src/components/Tooltip/index.ts
  packages/faency/src/index.ts
Labels: enhancement, status/3-needs-merge
