Repository traefik/faency, pull requests merged in 2020-02, with the labels that each got.

#44 doc: add information about the need to wrap app with the Faency provider
  README.md
Labels: status/3-needs-merge

#43 Nav and SubNav components are now responsive
  src/breakpoints.ts
  src/components/Nav/Nav.story.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/components/Menu.tsx
  src/components/Nav/components/MenuButton.tsx
  src/components/Nav/components/MenuIcon.tsx
  src/components/Nav/components/NavIcon.tsx
  src/components/Nav/index.ts
  src/components/Nav/utils/uuidv4.ts
  src/components/SubNav.story.tsx
  src/components/SubNav.tsx
Labels: status/3-needs-merge

#45 chore: bump to v0.3.2
  package-lock.json
  package.json
Labels: status/3-needs-merge

#46 feat: improve logo position in navbar
  package.json
  src/components/Nav/Nav.story.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/components/Menu.tsx
  src/components/Nav/index.ts
  src/index.ts
Labels: status/3-needs-merge

#47 chore: bump to v0.3.3
  package-lock.json
  package.json
Labels: status/3-needs-merge

#48 feat: add Select component
  package-lock.json
  package.json
  src/components/Chip.tsx
  src/components/Menu.tsx
  src/components/Select.story.tsx
  src/components/Select.tsx
Labels: enhancement, status/3-needs-merge

#50 feat: Add Radio component
  src/components/Radio.story.tsx
  src/components/Radio.tsx
Labels: enhancement, status/3-needs-merge

#49 Add Checkbox component
  .gitignore
  src/components/Checkbox.story.tsx
  src/components/Checkbox.tsx
  src/types/index.d.ts
Labels: enhancement, status/3-needs-merge

#62 doc: fix doc website deployment
  .travis.yml
  package.json
  packages/website/gatsby-config.js
  packages/website/package.json
  packages/website/src/App.js
  packages/website/src/components/Layout.js
Labels: status/3-needs-merge

#64 fix: use same github token env variable name as travis conf
  packages/website/package.json
Labels: bug, status/3-needs-merge

#63 Add CardLink component
  packages/faency/src/components/CardLink.story.tsx
  packages/faency/src/components/CardLink.test.tsx
  packages/faency/src/components/CardLink.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/card-link.mdx
Labels: status/3-needs-merge

#68 Add FormMessage component
  packages/faency/package.json
  packages/faency/src/components/FormMessage.story.tsx
  packages/faency/src/components/FormMessage.test.tsx
  packages/faency/src/components/FormMessage.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/form-message.mdx
  packages/website/src/templates/doc-page.js
  yarn.lock
Labels: status/3-needs-merge

#61 Add InputTags component
  packages/faency/package.json
  packages/faency/src/components/Chip.tsx
  packages/faency/src/components/DismissibleChip.tsx
  packages/faency/src/components/InputTags.story.tsx
  packages/faency/src/components/InputTags.test.tsx
  packages/faency/src/components/InputTags.tsx
  packages/faency/src/index.ts
  packages/website/src/docs/input-tags.mdx
  yarn.lock
Labels: status/3-needs-merge
