Repository traefik/faency, pull requests merged in 2021-12, with the labels that each got.

#212 fix: Input, pass DOM node through useImperativehandle
  components/Input/Input.tsx
Labels: status/3-needs-merge

#214 Fix: dialog overlay broken
  components/Overlay.tsx
Labels: status/3-needs-merge

#197 Feat: update tooltip styles
  components/IconButton/IconButton.tsx
  components/Input/Input.stories.tsx
  components/Input/index.ts
  components/Label/Label.stories.tsx
  components/Switch/Switch.stories.tsx
  components/Switch/Switch.tsx
  components/Switch/index.tsx
  components/Text/Text.stories.tsx
  components/TextField/TextField.tsx
  components/Tooltip/Tooltip.stories.tsx
  components/Tooltip/Tooltip.themes.ts
  components/Tooltip/Tooltip.tsx
  stitches.config.ts
Labels: enhancement, status/3-needs-merge

#199 fix: Select, proper variants and props typing
  components/Select/Select.tsx
Labels: kind/bug, status/3-needs-merge

#217 fix: Dialog story, proper use of Dialog and DialogTrigger
  components/Dialog/Dialog.stories.tsx
Labels: status/3-needs-merge, kind/bug/fix

#223 chore: release v1.0.0-5
  package-lock.json
  package.json
Labels: status/3-needs-merge

#221 feat: badge cleanup
  components/Badge/Badge.stories.tsx
  components/Badge/Badge.themes.ts
  components/Badge/Badge.tsx
  package-lock.json
  package.json
Labels: enhancement, status/3-needs-merge

#225 chore: remove unused components
  components/AlertDialog.tsx
  components/AppBar.tsx
  components/Code.tsx
  components/ControlGroup.tsx
  components/Kbd.tsx
  components/RadioCard.tsx
  components/RadioGrid.tsx
  components/Scrollbar.tsx
  components/Section.tsx
  components/Separator.tsx
  components/Sheet.tsx
  components/SimpleToggle.tsx
  components/Slider.tsx
  components/Sub.tsx
  components/Sup.tsx
  components/TabLink.tsx
  components/Tabs.tsx
  components/TextArea.tsx
  components/TreeItem.tsx
  index.ts
Labels: enhancement, status/3-needs-merge

#226 feat: skeleton, add badge variant
  components/Skeleton/Skeleton.stories.tsx
  components/Skeleton/Skeleton.tsx
Labels: enhancement, status/3-needs-merge

#229 feat: bubble update largest size
  components/Bubble/Bubble.stories.tsx
  components/Bubble/Bubble.tsx
Labels: enhancement, status/3-needs-merge
