Repository traefik/faency, pull requests merged in 2021-01, with the labels that each got.

#127 Update components Input, Card and CardLink
  packages/faency/src/components/Autocomplete.tsx
  packages/faency/src/components/Card.tsx
  packages/faency/src/components/Input.story.tsx
  packages/faency/src/components/Input.tsx
  packages/faency/src/components/Select.story.tsx
  packages/faency/src/components/Select.tsx
  packages/faency/src/theme.ts
Labels: enhancement, status/3-needs-merge

#128 Release v0.8.0
  lerna.json
  packages/faency/package.json
  packages/website/package.json
Labels: status/3-needs-merge

#129 Fix input background
  packages/faency/.storybook/config.js
  packages/faency/src/components/Input.tsx
Labels: kind/bug, status/3-needs-merge

#130 Release v0.8.1
  lerna.json
  packages/faency/package.json
  packages/website/package.json
Labels: status/3-needs-merge

#132 Sync input style between website and Faency
  packages/faency/src/components/Autocomplete.tsx
  packages/faency/src/components/Input.tsx
  packages/faency/src/components/Select.tsx
  packages/faency/src/fonts/Nunito-Bold.woff
  packages/faency/src/fonts/Nunito-Bold.woff2
  packages/faency/src/fonts/Nunito-Regular.woff
  packages/faency/src/fonts/Nunito-Regular.woff2
  packages/faency/src/fonts/Nunito-SemiBold.woff
  packages/faency/src/fonts/Nunito-SemiBold.woff2
  packages/faency/src/fonts/Rubik-Bold.woff2
  packages/faency/src/fonts/Rubik-Regular.woff2
  packages/faency/src/fonts/Rubik-SemiBold.woff2
  packages/faency/src/fonts/index.ts
  packages/faency/src/theme.ts
Labels: status/3-needs-merge
