Repository traefik/faency, pull requests merged in 2021-11, with the labels that each got.

#160 Update input style
  colors/deepBlue.ts
  colors/grayBlue.ts
  components/Flex/Flex.tsx
  components/IconButton/IconButton.tsx
  components/Input/Input.stories.tsx
  components/Input/Input.themes.ts
  components/Input/Input.tsx
  components/Input/index.ts
  components/Label/Label.stories.tsx
  components/Label/Label.tsx
  components/Text/Text.stories.tsx
  components/Text/Text.themes.ts
  components/Text/Text.tsx
  components/TextField/TextField.stories.tsx
  components/TextField/TextField.themes.ts
  components/TextField/TextField.tsx
  stitches.config.ts
  stories/examples/dashboard.stories.tsx
  stories/examples/form.stories.tsx
Labels: status/1-needs-design-review, status/3-needs-merge

#173 Input feedback
  components/Input/Input.tsx
  components/TextField/TextField.tsx
Labels: status/2-needs-review, status/3-needs-merge

#172 fix: Card interactive, add cursor pointer
  components/Card/Card.tsx
Labels: kind/bug, status/3-needs-merge

#169 feat: add navigation components
  .storybook/preview.js
  .vscode/settings.json
  colors/index.ts
  components/Badge/Badge.themes.ts
  components/Button/Button.themes.ts
  components/Card/Card.themes.ts
  components/Checkbox/Checkbox.themes.ts
  components/Dialog/Dialog.themes.ts
  components/FaencyProvider.tsx
  components/IconButton/IconButton.themes.ts
  components/Input/Input.themes.ts
  components/Link/Link.themes.ts
  components/Navigation/Navigation.stories.tsx
  components/Navigation/Navigation.themes.ts
  components/Navigation/Navigation.tsx
  components/Navigation/NavigationItem.stories.tsx
  components/Navigation/index.ts
  components/Radio/Radio.themes.ts
  components/Select/Select.themes.ts
  components/Skeleton/Skeleton.themes.ts
  components/Table/Table.themes.ts
  components/Text/Text.themes.ts
  package-lock.json
  package.json
  stitches.config.ts
  utils/getPrimaryColorInfo.ts
  utils/tokenToPropertyName.ts
Labels: status/3-needs-merge

#176 chore: update radix primitives
  package.json
Labels: status/3-needs-merge

#177 chore: release v1.0.0-2
  package-lock.json
  package.json
Labels: status/3-needs-merge

#182 fix: add missing navigation components exports
  components/Elevation/Elevation.tsx
  components/Navigation/Navigation.themes.ts
  components/Navigation/Navigation.tsx
  index.ts
Labels: kind/bug, status/3-needs-merge

#183 chore: release v1.0.0-3
  package-lock.json
  package.json
Labels: status/3-needs-merge

#179 fix: select style consistency with input one
  components/Input/Input.themes.ts
  components/Input/Input.tsx
  components/Select/Select.stories.tsx
  components/Select/Select.themes.ts
  components/Select/Select.tsx
Labels: status/3-needs-merge

#184 fix: alpha value on Navigation Item resting state
  components/Navigation/Navigation.tsx
Labels: status/3-needs-merge

#185 proposal: set background color based on elevation
  components/Elevation/Elevation.tsx
  components/Navigation/Navigation.tsx
Labels: status/3-needs-merge

#175 fix: input adornments josep feedback
  components/Input/Input.stories.tsx
  components/Input/Input.tsx
  components/TextField/TextField.tsx
Labels: enhancement, status/3-needs-merge

#186 chore: release v1.0.0-4
  package-lock.json
  package.json
Labels: status/3-needs-merge

#188 fix: import right colors const in colors story
  stitches.config.ts
  stories/colors.stories.tsx
Labels: status/3-needs-merge

#200 fix: Select, before and after, inherit borderRadius
  components/Select/Select.tsx
Labels: kind/bug, status/3-needs-merge

#201 chore: export elevationVariants
  components/Card/Card.tsx
  components/Dialog/Dialog.tsx
  components/Elevation/Elevation.tsx
  components/Input/Input.tsx
  components/Menu.tsx
  components/Navigation/Navigation.tsx
  components/Popover/Popover.tsx
  components/Select/Select.tsx
  components/Switch/Switch.tsx
  index.ts
Labels: enhancement, status/3-needs-merge

#203 Feat: add fontweights
  assets/fonts/rubik/OFL.txt
  assets/fonts/rubik/Rubik-Bold.woff2
  assets/fonts/rubik/Rubik-BoldItalic.woff2
  assets/fonts/rubik/Rubik-Italic.woff2
  assets/fonts/rubik/Rubik-Light.woff2
  assets/fonts/rubik/Rubik-LightItalic.woff2
  assets/fonts/rubik/Rubik-Medium.woff2
  assets/fonts/rubik/Rubik-MediumItalic.woff2
  assets/fonts/rubik/Rubik-Regular.woff2
  assets/fonts/rubik/Rubik-SemiBold.woff2
  assets/fonts/rubik/Rubik-SemiBoldItalic.woff2
  components/Avatar/Avatar.tsx
  components/Badge/Badge.tsx
  components/Button/Button.tsx
  components/FaencyProvider.tsx
  components/Heading/Heading.tsx
  components/Kbd.tsx
  components/Label/Label.tsx
  components/Navigation/Navigation.stories.tsx
  components/Navigation/Navigation.tsx
  components/Navigation/NavigationItem.stories.tsx
  components/Select/Select.tsx
  components/Table/Table.tsx
  stitches.config.ts
  stories/examples/form.stories.tsx
Labels: enhancement, status/3-needs-merge

#206 fix: FaencyProvider, global styles not called properly
  components/FaencyProvider.tsx
Labels: kind/bug, status/3-needs-merge
