Repository traefik/faency, pull requests merged in 2022-04, with the labels that each got.

#327 feat: export avatar
  index.ts
Labels: status/3-needs-merge

#331 fix: table default alignment
  components/AriaTable/AriaTable.stories.tsx
  components/Table/Table.tsx
Labels: status/3-needs-merge, kind/bug/fix, 00-type/task

#334 fix: button styles, cleanup themes
  components/Button/Button.themes.ts
  components/Button/Button.tsx
  components/Skeleton/Skeleton.stories.tsx
  components/Skeleton/Skeleton.tsx
Labels: status/3-needs-merge

#335 fix: dialog elevation
  components/Dialog/Dialog.stories.tsx
  components/Dialog/Dialog.tsx
Labels: status/3-needs-merge, 00-type/task, typescript/typings

#343 feat: IconButton, add contrast variant
  components/IconButton/IconButton.stories.tsx
  components/IconButton/IconButton.tsx
Labels: enhancement, status/3-needs-merge, 00-type/task

#207 fix: DocContainer, wrap with FaencyProvider
  .storybook/components/DocContainer.tsx
Labels: status/3-needs-merge

#357 feat: Text, add weight variants
  components/Text/Text.stories.tsx
  components/Text/Text.tsx
Labels: status/3-needs-merge

#352 feat: Skeleton, improve inferred display
  components/Skeleton/Skeleton.stories.tsx
  components/Skeleton/Skeleton.tsx
Labels: enhancement, status/3-needs-merge, 00-type/task

#346 chore!: reduce bundle size
  assets/fonts/rubik/OFL.txt
  assets/fonts/rubik/Rubik-Bold.woff2
  assets/fonts/rubik/Rubik-BoldItalic.woff2
  assets/fonts/rubik/Rubik-Italic.woff2
  assets/fonts/rubik/Rubik-Light.woff2
  assets/fonts/rubik/Rubik-LightItalic.woff2
  assets/fonts/rubik/Rubik-Medium.woff2
  assets/fonts/rubik/Rubik-MediumItalic.woff2
  assets/fonts/rubik/Rubik-Regular.woff2
  assets/fonts/rubik/Rubik-SemiBold.woff2
  assets/fonts/rubik/Rubik-SemiBoldItalic.woff2
  babel.config.js
  components/Accordion/Accordion.tsx
  components/Button/Button.themes.ts
  components/FaencyProvider.tsx
  components/Skeleton/Skeleton.stories.tsx
  components/Skeleton/Skeleton.tsx
  package-lock.json
  package.json
  rollup.config.js
  types/index.d.ts
Labels: status/3-needs-merge, kind/bug/fix

#354 feat: badge `asChild`
  components/Badge/Badge.stories.tsx
  components/Badge/Badge.test.tsx
  components/Badge/Badge.tsx
Labels: status/3-needs-merge

#355 feat: button `asChild`
  components/Button/Button.stories.tsx
  components/Button/Button.test.tsx
  components/Button/Button.tsx
Labels: status/3-needs-merge

#356 feat!: rework Heading
  components/Alert/Alert.stories.tsx
  components/Card/Card.stories.tsx
  components/Heading/Heading.stories.tsx
  components/Heading/Heading.test.tsx
  components/Heading/Heading.themes.ts
  components/Heading/Heading.tsx
  components/Skeleton/Skeleton.stories.tsx
  components/Table/Table.stories.tsx
  index.ts
  stitches.config.ts
Labels: status/3-needs-merge

#360 feat!: rework IconButton
  components/IconButton/IconButton.stories.tsx
  components/IconButton/IconButton.tsx
Labels: status/3-needs-merge

#365 fix: headings, disable user agent stylesheet margins
  components/Heading/Heading.tsx
Labels: status/3-needs-merge, kind/bug/fix

#369 chore: add license, Apache-2.0
  LICENSE
  package.json
Labels: area/documentation, status/3-needs-merge, 00-type/task

#367 chore: doc stories, no longer rely on Heading obsolete component
  .storybook/components/DocContainer.tsx
  stories/colors.stories.tsx
  stories/examples/dashboard.stories.tsx
  stories/examples/form.stories.tsx
Labels: status/3-needs-merge, kind/bug/fix

#363 feat: interactive components, improve focus outline
  components/Badge/Badge.tsx
  components/Card/Card.tsx
  components/Checkbox/Checkbox.tsx
  components/Link/Link.stories.tsx
  components/Select/Select.stories.tsx
  components/Switch/Switch.themes.ts
  components/Switch/Switch.tsx
  components/Textarea/Textarea.tsx
Labels: status/3-needs-merge

#364 feat: badge pressed state
  components/Badge/Badge.themes.ts
  components/Badge/Badge.tsx
Labels: enhancement, status/3-needs-merge, 00-type/task, area/a11y

#371 fix: Card Interactive, pressed behavior broken
  components/Card/Card.tsx
Labels: status/3-needs-merge

#340 feat!: make package an esModule, upgrade deps, update build path for cjs
  .storybook/main.cjs
  README.md
  babel.config.cjs
  jest.config.cjs
  package-lock.json
  package.json
  rollup.config.js
Labels: status/3-needs-merge, kind/bug/fix
