Repository traefik/faency, pull requests merged in 2022-07, with the labels that each got.

#378 fix: Input start adornment zIndex
  components/Input/Input.tsx
Labels: bot/light-review, status/3-needs-merge, kind/bug/fix

#380 feat: ButtonSwitch component
  .vscode/settings.json
  components/ButtonSwitch/ButtonSwitch.stories.tsx
  components/ButtonSwitch/ButtonSwitch.themes.ts
  components/ButtonSwitch/ButtonSwitch.tsx
  components/ButtonSwitch/index.ts
  package-lock.json
  package.json
  stitches.config.ts
Labels: enhancement, status/3-needs-merge

#382 fix: export ButtonSwitch component
  index.ts
Labels: bot/light-review, status/3-needs-merge
