Repository traefik/faency, pull requests merged in 2022-03, with the labels that each got.

#307 feat: add GitHub action pr title check b
  .github/workflows/pr_title.yml
  package-lock.json
  package.json
Labels: enhancement, status/3-needs-merge, 00-type/task

#308 chore: add PR template
  .github/pull_request_template.md
  README.md
Labels: area/documentation, enhancement, status/2-needs-review, status/3-needs-merge

#288 chore: add semantic release, preset conventionalcommits
  .github/pull_request_template.md
  .github/workflows/release.yml
  README.md
  package-lock.json
  package.json
Labels: area/documentation, enhancement, status/3-needs-merge, area/infrastructure

#313 docs: how to contribute, release process
  .github/pull_request_template.md
  README.md
Labels: area/documentation, status/3-needs-merge, 00-type/task

#314 feat: table empty layout improvements
  components/AriaTable/AriaTable.tsx
  components/Table/Table.stories.tsx
  components/Table/Table.tsx
Labels: enhancement, status/3-needs-merge

#316 fix: popover arrow color not customizable
  components/Popover/Popover.stories.tsx
  components/Popover/Popover.tsx
  index.ts
Labels: status/3-needs-merge, kind/bug/fix

#317 feat!: dialog export content without close icon
  components/Dialog/Dialog.stories.tsx
  components/Dialog/Dialog.tsx
  index.ts
Labels: status/3-needs-merge, 00-type/task

#321 chore: add project info to package.json
  package.json
Labels: enhancement, status/3-needs-merge

#322 fix: add build to release workflow
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, semantic-release

#195 feat: Text component, add inherit variants for fontSize and color
  components/Text/Text.stories.tsx
  components/Text/Text.tsx
Labels: enhancement, status/3-needs-merge

#319 feat: aria table colspan
  components/AriaTable/AriaTable.stories.tsx
  components/AriaTable/AriaTable.tsx
  components/Table/Table.tsx
Labels: enhancement, status/3-needs-merge, 00-type/task, area/a11y
