Repository traefik/faency, pull requests merged in 2022-02, with the labels that each got.

#270 feat: Radio, hover pointer
  components/Radio/Radio.tsx
Labels: enhancement, status/3-needs-merge

#237 feat: visuallyHidden + table accessible examples
  components/Table/Table.stories.tsx
  components/VisuallyHidden/VisuallyHidden.stories.tsx
  components/VisuallyHidden/VisuallyHidden.tsx
  components/VisuallyHidden/index.tsx
  index.ts
  package.json
Labels: documentation, enhancement, status/3-needs-merge, prio

#278 fix!: avoid init themes on Faency side causing them not being available on server side
  components/FaencyProvider.tsx
  index.ts
  package-lock.json
  package.json
  stitches.config.ts
Labels: status/3-needs-merge, kind/bug/fix

#277 chore: update Table styles
  components/Table/Table.stories.tsx
  components/Table/Table.themes.ts
  components/Table/Table.tsx
Labels: status/3-needs-merge

#276 chore: release v1.0.0-10
  package-lock.json
  package.json
Labels: bot/light-review, status/3-needs-merge

#282 fix: storybook theme + primary color
  .storybook/preview.js
Labels: status/3-needs-merge, kind/bug/fix

#281 fix: inherit `border-radius` on table children elements
  components/Table/Table.stories.tsx
  components/Table/Table.tsx
Labels: status/3-needs-merge, kind/bug/fix

#245 feat: improve breakpoints overlapping
  stitches.config.ts
Labels: enhancement, status/3-needs-merge

#284 chore: release v1.0.0-11
  package-lock.json
  package.json
Labels: bot/light-review, status/3-needs-merge

#287 feat: TextField, ReadonlyCopy story
  components/TextField/TextField.stories.tsx
Labels: enhancement, status/3-needs-merge, kind/task

#294 fix: kill css incompatible error
  components/Accordion/Accordion.stories.tsx
  components/Accordion/Accordion.tsx
  components/Alert/Alert.stories.tsx
  components/Alert/Alert.tsx
  components/AriaTable/AriaTable.stories.tsx
  components/AriaTable/AriaTable.tsx
  components/Avatar/Avatar.stories.tsx
  components/Badge/Badge.stories.tsx
  components/Box/Box.stories.tsx
  components/Bubble/Bubble.stories.tsx
  components/Button/Button.stories.tsx
  components/Button/Button.tsx
  components/Card/Card.stories.tsx
  components/Checkbox/Checkbox.stories.tsx
  components/Container/Container.stories.tsx
  components/Dialog/Dialog.stories.tsx
  components/DropdownMenu/DropdownMenu.stories.tsx
  components/Elevation/Elevation.stories.tsx
  components/Flex/Flex.stories.tsx
  components/Flex/Flex.tsx
  components/Grid/Grid.stories.tsx
  components/Grid/Grid.tsx
  components/Heading/Heading.stories.tsx
  components/Heading/Heading.tsx
  components/IconButton/IconButton.stories.tsx
  components/IconButton/IconButton.tsx
  components/Image/Image.stories.tsx
  components/Image/Image.tsx
  components/Input/Input.stories.tsx
  components/Input/Input.tsx
  components/Label/Label.stories.tsx
  components/Link/Link.stories.tsx
  components/Navigation/Navigation.stories.tsx
  components/Navigation/Navigation.tsx
  components/Popover/Popover.tsx
  components/Radio/Radio.stories.tsx
  components/RadioAccordion/RadioAccordion.stories.tsx
  components/RadioAccordion/RadioAccordion.tsx
  components/Select/Select.stories.tsx
  components/Select/Select.tsx
  components/Skeleton/Skeleton.tsx
  components/Switch/Switch.stories.tsx
  components/Table/Table.stories.tsx
  components/Text/Text.stories.tsx
  components/Text/Text.tsx
  components/TextField/TextField.stories.tsx
  components/Textarea/Textarea.stories.tsx
  components/Textarea/Textarea.tsx
  components/Tooltip/Tooltip.stories.tsx
  components/Tooltip/Tooltip.tsx
  tsconfig-rollup.json
  tsconfig.json
Labels: status/3-needs-merge, kind/bug/fix, prio

#295 feat: Textarea, add endAdornment
  components/Textarea/Textarea.stories.tsx
  components/Textarea/Textarea.tsx
Labels: enhancement, status/3-needs-merge, 00-type/task

#298 release: v1.0.0-12
  package-lock.json
  package.json
Labels: bot/light-review, status/3-needs-merge, prio, 00-type/task

#231 feat!: skeleton infer dimensions
  components/Skeleton/Skeleton.stories.tsx
  components/Skeleton/Skeleton.tsx
Labels: enhancement, status/3-needs-merge, kind/proposal
